const test=require('node:test');
const assert=require('node:assert/strict');
const m=require('../assets/tools/tempo-model');
function answers(values=['busy','interrupt','postponed',3,30]){return ['feeling','pattern','effect','days','minutes'].reduce((s,k,i)=>m.choose(s,k,values[i]),m.fresh());}
test('five answers form a personal path and one calculation',()=>{const s=answers();assert.ok(m.complete(s));assert.deepEqual(m.estimate(s),{kind:'estimate',periodMinutes:90,monthlyMinutes:396});assert.match(m.question(s,1).context,/principal/);assert.match(m.question(s,2).title,/interrompeu/);assert.match(m.question(s,3).context,/depois/);assert.match(m.question(s,4).context,/Retomar/);});
test('each source of friction has its own question and observation',()=>{for(const pattern of ['interrupt','search','redo','wait']){const s=answers(['on',pattern,'overtime',2,15]);assert.ok(m.question(s,2).title);assert.equal(m.question(s,4).context,m.patterns[pattern].timeContext);assert.ok(m.patterns[pattern].observation);}assert.match(m.patterns.wait.hint,/Exclua/);});
test('a calm answer changes the next question without assuming distress',()=>{const s=m.choose(m.fresh(),'feeling','calm');assert.match(m.question(s,1).title,/alguma coisa/);assert.match(m.question(s,1).hint,/último dia/);});
test('none ends after two answers without manufacturing a time loss',()=>{const s=answers(['calm','none','delayed',5,120]);assert.equal(m.lastStep(s),1);assert.ok(m.complete(s));assert.deepEqual(m.estimate(s),{kind:'outside'});assert.equal(s.effect,null);assert.equal(s.minutes,null);});
test('unknown frequency or duration yields a qualitative result',()=>{for(const values of [['busy','search','postponed','unknown',30],['busy','search','postponed',3,'unknown'],['busy','search','postponed','unknown','unknown']]){assert.deepEqual(m.estimate(answers(values)),{kind:'unquantified'});}});
test('zero is zero, including unknown frequency',()=>{for(const days of [1,'unknown'])assert.deepEqual(m.estimate(answers(['calm','wait','okay',days,0])),{kind:'zero',periodMinutes:0,monthlyMinutes:0});});
test('changing an upstream answer clears only downstream evidence',()=>{const s=answers();const same=m.choose(s,'pattern','interrupt');assert.equal(same.minutes,30);const changed=m.choose(s,'pattern','search');assert.equal(changed.feeling,'busy');assert.equal(changed.effect,null);assert.equal(changed.days,null);assert.equal(changed.minutes,null);assert.equal(m.estimate(changed),null);});
test('old states and forged enum keys cannot contaminate the new questionnaire',()=>{assert.deepEqual(m.sanitize({version:2,task:'old'}),m.fresh());assert.deepEqual(m.sanitize({version:3,feeling:'__proto__',pattern:'search',minutes:30}),m.fresh());});
test('invalid numbers remain incomplete; custom whole minutes are accepted',()=>{for(const minutes of [-1,481,1.5,NaN,Infinity,'30'])assert.equal(m.estimate(answers(['busy','redo','delayed',2,minutes])),null);assert.equal(m.estimate(answers(['busy','redo','delayed',2,37])).periodMinutes,74);for(const days of [0,6,2.5])assert.equal(m.estimate(answers(['busy','redo','delayed',days,30])),null);});
test('incomplete paths do not invent estimates and formatting remains human',()=>{assert.equal(m.estimate(m.fresh()),null);assert.equal(m.formatMinutes(90),'1h 30min');assert.equal(m.formatMinutes(60),'1h');assert.equal(m.formatMinutes(0),'0 min');});
